site_name: DMX
site_url : https://yanis-kouidri.github.io/DMX/
repo_url: https://github.com/yanis-kouidri/DMX
repo_name: yanis-kouidri/DMX
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Data Mule: data_mule.md
  - DTN: dtn.md
  - Edge Computing: edge_computing.md
  - Multi-RAT: multi_rat.md
  - UAV: uav.md
  - Routing: routing.md
  - Glossary: glossary.md
theme:
  name: material
  logo: assets/mule.png
  favicon: assets/mule.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - content.action.edit
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      scheme: default

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css