site_name: DMX
site_url : https://yanis-kouidri.github.io/DMX/
nav:
  - Home: index.md
  - Data Mule: data_mule.md
  - DTN: dtn.md
  - Edge Computing: edge_computing.md
  - Multi-RAT: multi_rat.md
  - UAV: uav.md
  - Routing: routing.md
  - Glossary: glossary.md
theme:
  name: material
  logo: assets/mule.png
  favicon: assets/mule.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      scheme: default

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
