name: publish
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install python
        uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true

      - name: install dependencies
        run: uv sync --frozen

      - name: Deploy documentation on GitHub Pages
        run: uv run mkdocs gh-deploy --force
      